ALTER TABLE theses
    ADD COLUMN IF NOT EXISTS structure TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS legs JSONB DEFAULT '[]'::jsonb;

ALTER TABLE positions
    ADD COLUMN IF NOT EXISTS structure TEXT DEFAULT '',
    ADD COLUMN IF NOT EXISTS legs JSONB DEFAULT '[]'::jsonb;
