ALTER TABLE competence_states
    ADD COLUMN IF NOT EXISTS trust_ceiling DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    ADD COLUMN IF NOT EXISTS confidence_ceiling DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    ADD COLUMN IF NOT EXISTS validated_outcomes INTEGER NOT NULL DEFAULT 0;
